### ISSUE TITLE
Array index out of bounds when adding new vertex.

### ISSUE THREAD

**Issue by 3asier** [wilsam239/Untangled#6] opened 2019-12-04 22:52 UTC
Happens at line 69 of LevelEditor.pde
Can be reproduced as follows:
- Open level editor.
- Place a vertex at any position
- Position the mouse such that it is just outside the bounding box of the first vertex.
- Attempt to place a vertex. <- Error happens here.

This occurs because the game cannot place the second vertex because it is too close to the first.  So it then assumes that there should be a vertex that it is trying to select (but there isn't one).

![image](https://user-images.githubusercontent.com/45731048/70233752-4c01e980-17b3-11ea-93d7-4f5d9a3478fd.png)

**Comment by wilsam239** [comment] 2019-12-06 09:15
Issue resolved in commit 883de06aff743639476a618e7101297c87618516 on 6/12/19 at 8:13pm. Issue was caused by mousedVertex returning -1, and not checking if it was -1 when attempting to move a vertex.

**Closed as completed by wilsam239** 2019-12-06 09:15 UTC
Labels: bug
